name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: >-
      github.event.pull_request.merged == true
      && startsWith(github.event.pull_request.head.ref, 'tagpr-from')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --filter=tree:0 --deepen=1 origin $BRANCH_NAME
          latest_tag=$(git describe --tags --abbrev=0)
          gh release create "$latest_tag" \
            --title="$latest_tag" \
            main.js manifest.json
