name: tagpr

on:
  push:
    branches:
    - main

jobs:
  tagpr:
    # TODO: tagprのPRがマージされたときは実行したくない
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_FOR_TAGPR }}

    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_FOR_TAGPR }}
